Repository TopAcademy2022/simple-weather-guide, pull requests merged in 2025-04, with the labels that each got.

#11 Moved to typescript. Closed #10
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.js
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: enhancement

#14 Added get data from api. Closed #6
  .gitignore
  package.json
  src/domain/interfaces/iweather-service.ts
  src/infrastruction/services/weather-service.ts
Labels: enhancement

#15 Added Github action. Closed #12
  .github/workflows/node.js.yml
Labels: testing

#17 Fix github action. Closed #16
  .github/workflows/node.js.yml
  src/App.test.tsx
Labels: bug, testing

#18 Added render current weather. Closed #7
  package.json
  src/App.test.tsx
  src/App.tsx
  src/domain/models/weather.ts
  src/index.tsx
  src/infrastruction/services/weather-service.ts
  src/setupTests.ts
  src/tests/ui/App.test.tsx
  src/ui/components/App.tsx
  src/ui/components/CurrentWeather.tsx
Labels: enhancement

#21 Added render hourly weather. Closed #8
  src/domain/interfaces/iweather-service.ts
  src/domain/models/weather.ts
  src/infrastruction/services/weather-service.ts
  src/script.js
  src/ui/components/App.tsx
  src/ui/components/HourlyPrint.tsx
Labels: enhancement
